jobs:
  - job: Linux
    displayName: T
    pool:
      vmImage: ubuntu-20.04
    strategy:
      matrix:
        CentOS 8:
          MOLECULE_DISTRIBUTION: centos8

    steps:
      - checkout: self
        path: ansibullbot

      - script: pip3 install yamllint molecule molecule-docker ansible-core docker
        displayName: Setup

      - script: /home/vsts/.local/bin/yamllint -c molecule/yamllint.yml $(Build.Repository.LocalPath)
        displayName: Lint

      - script: |
          export PATH=/home/vsts/.local/bin:$PATH
          ansible-galaxy install -r molecule/requirements.yml
          molecule test
        displayName: Molecule
        workingDirectory: $(Build.Repository.LocalPath)
        env:
          PY_COLORS: 1
