# Only needed due monitoring via CGI script. Once that is changed, SELinux
# can be set to Enforcing again.
- name: Enable SELinux
  selinux:
    state: enforcing
    policy: targeted
  tags:
    - ansibullbot
    - ansibullbot_selinux
    - notest

- name: Set hostname
  hostname:
    name: "{{ ansibullbot_fqdn }}"
  tags:
    - ansibullbot
    - ansibullbot_hostname
    - notest

- name: Install packages
  yum:
    name: "{{ ansibullbot_packages }}"
    state: latest
  tags:
    - ansibullbot
    - packages

- name: Create {{ ansibullbot_group }} group
  group:
    name: "{{ ansibullbot_group }}"
    gid: '1099'
  tags:
    - ansibullbot
    - user

- name: Create {{ ansibullbot_user }} account
  user:
    name: "{{ ansibullbot_user }}"
    home: "{{ ansibullbot_home_dir }}"
    uid: '1099'
  tags:
    - ansibullbot
    - user

- name: Set ssh authorized_keys for centos
  authorized_key:
    key: "{{ item.key_material }}"
    user: centos
    comment: "{{ item.commend | default(item.name) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ botinstance_ssh_keys }}"
  tags:
    - ansibullbot
    - ssh

- name: Set ssh authorized_keys for {{ ansibullbot_user }}
  authorized_key:
    key: "{{ item.key_material }}"
    user: "{{ ansibullbot_user }}"
    comment: "{{ item.commend | default(item.name) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ botinstance_ssh_keys }}"
  tags:
    - ansibullbot
    - ssh

- name: Copy dotfiles for root
  copy:
    src: "{{ item }}"
    dest: ~root/.{{ item | basename }}
    owner: root
    group: root
  with_fileglob: dotfiles/*
  tags:
    - ansibullbot
    - ansibullbot_dotfiles

- name: Copy ansibullbot.cfg
  template:
    src: ansibullbot.cfg.j2
    dest: ~{{ ansibullbot_user }}/.ansibullbot.cfg
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
    mode: '0600'
  notify: restart ansibullbot
  tags:
    - ansibullbot
    - ansibullbot_dotfiles

- name: Checkout git repo
  git:
    repo: "{{ ansibullbot_repo_url }}"
    dest: "{{ ansibullbot_clone_path }}"
    refspec: "{{ ansibullbot_branch }}"
    recursive: yes
    force: yes
  become: yes
  become_user: "{{ ansibullbot_user }}"
  tags:
    - ansibullbot
    - ansibullbot_git
    - ansibullbot_update

- name: Install Python requirements
  pip:
    requirements: "{{ ansibullbot_clone_path }}/requirements.txt"
  tags:
    - ansibullbot
    - ansibullbot_pip
    - ansibullbot_update

- name: Download stopwords
  shell: python -c 'import nltk; nltk.download("punkt")'
  become_user: "{{ ansibullbot_user }}"
  become: yes
  args:
    creates: ~{{ ansibullbot_user }}/nltk_data
  tags:
    - ansibullbot
    - ansibullbot_nltk_data

- import_tasks: ansibullbot_service.yml

- import_tasks: ansibullbot_receiver_service.yml
  when: ansibullbot_receiver_enabled
