- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml
      paths:
        - vars
  tags:
    - ansibullbot

- include_tasks: "{{ ansibullbot_action }}/main.yml"
  tags:
    - ansibullbot
    - ansibullbot_cache
    - ansibullbot_cron
    - ansibullbot_dotfiles
    - ansibullbot_git
    - ansibullbot_logs
    - ansibullbot_pip
    - ansibullbot_receiver
    - ansibullbot_service
    - ansibullbot_selinux
    - ansibullbot_update
    - ssh
    - user
    - packages

- import_tasks: monitoring.yml
