- name: MONITORING | Create web directories
  file:
    path: "{{ item.path | default(item) }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: '0755'
  loop:
    - path: "{{ caddy_root }}/cgi-bin"
    - path: "{{ caddy_root }}/ansibot/html"
    - path: "{{ caddy_root }}/ansibot/html/metadata"
      owner: "{{ ansibullbot_user }}"
      group: "{{ ansibullbot_group }}"
    - path: "{{ ansibullbot_caddy_log_path }}"
      owner: "{{ caddy_user }}"
      group: "{{ caddy_group }}"
  tags:
    - ansibullbot
    - ansibullbot_monitoring

- name: MONITORING | Copy HTML files
  copy:
    src: "{{ item }}"
    dest: "{{ caddy_root }}/ansibot/html/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - index.html
    - error.html
  tags:
    - ansibullbot
    - ansibullbot_monitoring

- name: MONITORING | Copy monitoring script
  copy:
    src: "{{ ansibullbot_clone_path ~ '/scripts/ansibot_status.cgi' }}"
    dest: "{{ caddy_root }}/cgi-bin/ansibot_status.cgi"
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  tags:
    - ansibullbot
    - ansibullbot_monitoring

- name: MONITORING | Add caddy user account to {{ ansibullbot_group }} group
  user:
    name: "{{ caddy_user }}"
    groups: "{{ ansibullbot_group }}"
    append: yes
  tags:
    - ansibullbot
    - ansibullbot_monitoring

- name: MONITORING | Set permissions on ansibullbot home
  file:
    path: "{{ ansibullbot_home_dir }}"
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
    mode: 'g+rx'
  tags:
    - ansibullbot
    - ansibullbot_monitoring

- name: MONITORING | Set permissions on ansibullbot code checkout
  file:
    path: "{{ ansibullbot_clone_path }}"
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
    recurse: yes
    mode: 'g+r'
  tags:
    - ansibullbot
    - ansibullbot_monitoring

- name: MONITORING | Copy Caddy config file
  template:
    src: Caddyfile_ansibullbot.j2
    dest: "{{ caddy_config_path }}/conf.d/ansibullbot"
    lstrip_blocks: yes
    owner: root
    group: root
    mode: '0644'
  notify: reload caddy
  tags:
    - ansibullbot
    - ansibullbot_monitoring
