- name: Get latest revision
  git:
    repo: "{{ ansibullbot_repo_url }}"
    dest: "{{ ansibullbot_clone_path }}"
    refspec: "{{ ansibullbot_branch }}"
    force: yes
  become: yes
  become_user: "{{ ansibullbot_user }}"
  notify:
    - send slack message
    - restart ansibullbot
  tags:
    - ansibullbot_git
    - ansibullbot_update

- name: Install Python requirements
  pip:
    requirements: "{{ ansibullbot_clone_path }}/requirements.txt"
  tags:
    - ansibullbot_pip
    - ansibullbot_update

- name: Copy ansibullbot.cfg
  template:
    src: ansibullbot.cfg.j2
    dest: ~{{ ansibullbot_user }}/.ansibullbot.cfg
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
    mode: '0600'
  tags:
    - ansibullbot_dotfiles
    - ansibullbot_update

- name: Copy ansibullbot service file
  template:
    src: systemd_ansibullbot.j2
    dest: /etc/systemd/system/ansibullbot.service
    owner: root
    group: root
    mode: '0644'
  notify: restart ansibullbot
  tags:
    - ansibullbot_service
    - ansibullbot_update

- name: Copy ansibullbot-receiver service file
  template:
    src: systemd_ansibullbot_receiver.j2
    dest: /etc/systemd/system/ansibullbot-receiver.service
    owner: root
    group: root
    mode: '0644'
  notify: restart ansibullbot-receiver
  tags:
    - ansibullbot_service
    - ansibullbot_update

- name: Copy monitoring script
  copy:
    src: "{{ ansibullbot_clone_path ~ '/scripts/ansibot_status.cgi' }}"
    dest: "{{ caddy_root }}/cgi-bin/ansibot_status.cgi"
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  tags:
    - ansibullbot_monitoring

- name: Copy Caddy config file
  template:
    src: caddy_ansibullbot.conf.j2
    dest: "{{ caddy_config_path }}/conf.d/ansibullbot.conf"
  notify: reload caddy
  tags:
    - ansibullbot
    - ansibullbot_monitoring
