- hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - debug:
        msg: >-
          Testing with Ansible {{ ansible_version.full }} using Python {{ ansible_facts.python_version }}
          on {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}

    - name: Create centos group
      group:
        name: centos

    - name: Create centos user
      user:
        name: centos

    - import_role:
        name: repo_epel

    - import_role:
        name: caddy

    - import_role:
        name: ansibullbot
