dependency:
  name: galaxy
  enabled: no
driver:
  name: docker
lint: |
  ansible-lint -x 204,401,403,502 --exclude molecule/default/converge.yml
  yamllint -c molecule/default/yamllint.yml .
platforms:
  - name: ansibullbot-test-${MOLECULE_DISTRIBUTION:-centos8}
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos8}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: ansible.posix.debug
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  options:
    skip-tags: notest
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
